### PR TITLE
Added in Instant KO

### PR DESCRIPTION
**Pull request by Crain-32**
Added in Instant KO along with a checkbox for it.

Patches were tested on my Multiworld branch before moving them here. Python's "amazing" virtual env wasn't working, so I've tested what I can, and was going to use the PR build to double check everything. Included an `Instant KO` checkbox as well.

### CODE REVIEW

**Comment by wooferzfg** [comment]
There should be changes to `wwr_ui/ui_randomizer_window.py` to correspond to the `randomizer_window.ui` changes

**Comment by Crain-32** [comment]
When I run `pyside6-uic randomizer_window.ui -> ui_randomizer_window.py`, it deletes the Plando Buttons, but my PR doesn't remove them. Did they get removed from the `.ui` file during the 1.10 merge?

**Comment by wooferzfg** [comment]
Oh, I think those were never added to the UI file for some reason (like even before updating the plando for 1.10). I would suggest running `pyside6-uic randomizer_window.ui` and then manually adding the changes for the plando from [here](https://github.com/wooferzfg/wwrando/commit/4ca6d44fbd94418dfd6405403e058641560a6f69#diff-0becadbfac3a180ae8d6c20ae1f20548c433d915b3f24ea14ab348badcb83fbf) (or I could do that last part for you, if you push your changes to `ui_randomizer_window.py`)

**Comment by Crain-32** [comment]
I have the `ui_randomizer_window.py` changes locally, I'll push them up. Just wanted to check on the plando stuff first. If you could do the plando changes post merge that would be great. I'm really not used to QT.

**Comment by wooferzfg** [comment]
@Crain-32 I pushed the changes. If you could test them out, that would be helpful (I also pushed a commit to enable GitHub Actions)

**Comment by Crain-32** [comment]
I'll check out the visual changes after the build is done, but probably won't get to confirming the patches till Saturday.

**Comment by Crain-32** [comment]
I'll take a deeper look into these issues on Saturday.

**Comment by Crain-32** [comment]
@wooferzfg Sorry for not finishing up this PR, I've been busy. But I'm finally back in a situation to clean it up.
image

The build for Windows is working, but it's missing the module "aes". I'm seeing two different modules in the `requirements.txt` and `requirements_full.txt`. I'm not sure if this is an issue due to the build pipeline changes, or something else.

**Comment by wooferzfg** [comment]
`pyaes` is missing from `requirements_full.txt`. You can keep `tinyaes` in there

**Comment by Crain-32** [comment]
To prevent you from getting Spam emails from my failed builds I tested adding
`pyaes=1.6.1` to `requirements_full.txt` on another branch and PRed to `instant-ko`, I'm still getting the missing aes module error.

**Pull request closed without merging**
